name: devpaul_todo_app
description: "DevPaul ToDo - ToDo App + AI Assistant"

version: 1.1.17+19

environment:
  sdk: ^3.5.0-323.2.beta

dependencies:
  archive: ^4.0.7
  bloc: ^9.0.0
  cloud_firestore: ^5.3.0
  cupertino_icons: ^1.0.8
  equatable: ^2.0.5
  firebase_auth: ^5.2.0
  firebase_core: ^3.4.0
  firebase_storage: ^12.3.1
  flutter:
    sdk: flutter
  flutter_bloc: ^9.1.1
  flutter_dotenv: ^5.2.1
  flutter_markdown: ^0.7.7
  flutter_secure_storage: ^9.2.2
  flutter_svg: ^2.0.10+1
  get_it: ^8.0.3
  go_router: ^15.1.1
  google_fonts: ^6.2.1
  http: ^1.2.2
  image_picker: ^1.1.2
  intl: ^0.20.2
  markdown: ^7.2.2
  package_info_plus: ^8.0.3
  path_provider: ^2.1.5
  pdf: ^3.11.1
  permission_handler: ^12.0.0+1
  printing: ^5.13.4
  share_plus: ^11.0.0
  shared_preferences: ^2.5.3
  signature: ^6.0.0
  url_launcher: ^6.3.1

dev_dependencies:
  flutter_launcher_icons: ^0.14.3
  flutter_lints: ^5.0.0
  flutter_test:
    sdk: flutter

flutter_launcher_icons:
  android: "launcher_icon"
  ios: true
  image_path: "assets/logo.png"
  min_sdk_android: 21
  web:
    generate: true
    image_path: "assets/logo.png"
    background_color: "#hexcode"
    theme_color: "#FFFFFF"

flutter:
  uses-material-design: true
  assets:
    - assets/
    - assets/social/
    - .env
